### ISSUE TITLE
0.0.2 Tag checksum changed?

### ISSUE THREAD

**Issue by cdyson37** [palantir/python-jsonrpc-server#20]
Was the content of the 0.0.2 tag deliberately changed? In NixOS it used to be a different checksum for the same URL. Please see https://github.com/NixOS/nixpkgs/issues/64485

(Edited so I sound less silly)

**Comment by gatesn** [comment]
I don't know how that happened I'm afraid? We just cut `0.2.0`, but not `0.0.2`

**Comment by cdyson37** [comment]
It would have happened a while ago probably. See NixOS bug, it was probably a version number fix made after the original release. I don't think it's a problem, sorry for the time wasting.
