### ISSUE TITLE
Requesting maintenance permissions on this repo

### ISSUE THREAD

**Issue by ccordoba12** [palantir/python-jsonrpc-server#42]
@gatesn, in order to keep maintaining the Python language server and move forward with the transition to Python 3 (as we agreed on), I'd like to kindly ask you to grant me write permissions to this repo.

Also, it'd be great if you could also grant me admin permissions (here and in the PyLS) so I could move their CIs to Github actions. However, I'd understand if that's not possible due to company policies.

Hope to hear from you soon,
Carlos

**Comment by ccordoba12** [comment]
Pinging @gatesn again about this. Sorry to bother you again but we're totally stuck due to this.

Could you grant me permissions to this repo so I can maintain this package?

**Comment by gatesn** [comment]
Apologies, I'm no longer actively working in this space. 

I believe @delta003 should be able to help you with this.

**Comment by ccordoba12** [comment]
No problem and thanks for your answer @gatesn!

Hope to hear from @delta003 soon.

**Comment by ccordoba12** [comment]
@delta003, any news about this? We'd really like not to split the community by creating a fork of this and `python-language-server`. But we're stuck at the moment because we can't update this package nor migrate it to Python 3.

Please let me know if you need something else from my side to move forward. Thanks!

**Comment by uschi2000** [comment]
@ccordoba12 I will sort this out today, sorry about the delay.

**Comment by ccordoba12** [comment]
Great news! Thanks a lot for your help @uschi2000!

**Comment by uschi2000** [comment]
@ccordoba12 I haven't managed to get the required code review internally yet, because my colleague is in CA and likely hasn't seen my PR yet. I hope to get the review through today US time so I can apply the permissions changes tomorrow EU time.

**Comment by ccordoba12** [comment]
No problem, thanks a lot for letting me know about it.

**Comment by uschi2000** [comment]
I added @ccordoba12 and @goanpeca with "write" access. Thanks for your patience, folks.

**Comment by ccordoba12** [comment]
Thanks a lot for your help @uschi2000! This and `python-language-server` are very important projects for lots of IDEs and editors, and I'm glad you're trusting me to maintain them.
