### ISSUE TITLE
Missing 0.4.0 tag in the repository

### ISSUE THREAD

**Issue by Foxboron** [palantir/python-jsonrpc-server#48]
Seems like some 0.4.0 version of this library has been updated on pypi, but there hasn't been any tags on this repository.
Please confirm the release is legitimate as there isn't any signatures anywhere :)

https://pypi.org/project/python-jsonrpc-server/0.4.0/

**Comment by ccordoba12** [comment]
It is legitimate. The next release of `python-language-server` will depend on it.

@delta003, could you tag the commit from which you created this release? Thanks!

**Comment by bnavigator** [comment]
How about a changelog, too?

**Comment by ccordoba12** [comment]
Good idea! I'll try to add one for future releases.

**Comment by delta003** [comment]
Tagged 0.4.0
